//leetcode389:Find the Difference
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <unordered_map>

using namespace std;

class Solution {
public:
	char findTheDifference(string s, string t) {
		unordered_map<char, int> dictS, dictT;
		char res;
		for (auto i : s) {
			dictS[i]++;
		}
		for (auto i : t) {
			dictT[i]++;
		}
		for (auto i : dictT) {
			if (i.second != dictS[i.first]) {
				res = i.first;
				break;
			}
		}
		return res;
	}
};